### ISSUE TITLE
Error compiling sample

### ISSUE THREAD

**Issue by nikolacicmil** [BlinkIDscan/blinkid-ios#2]
Getting this error when compiling the sample project:
2015-02-26 18:47:57.466 BlinkID-sample[3712:328858] Version is 0.6.0
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /Users/cerovec/Tools/opencv/modules/core/src/matrix.cpp, line 322
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/cerovec/Tools/opencv/modules/core/src/matrix.cpp:322: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

**Comment by Cerovec** [comment]
Hi,

compiling the sample project for iOS devices works for us in Xcode 6.1.1.
We did, however, see issues when linking the app for iOS Simulator, but that's another issue.

Can you elaborate more in which circumstances this error occurs?

Best regards,
Jurica.

**Comment by Cerovec** [comment]
Closed as inactive.
